# Generated by Django 5.2.4 on 2026-06-23 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('voltage', models.CharField(blank=True, max_length=20, null=True)),
                ('plug_type', models.CharField(blank=True, max_length=20, null=True)),
                ('adapter_needed', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CitySafety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_index', models.FloatField(null=True)),
                ('safe_alone_day', models.FloatField(null=True)),
                ('safe_alone_night', models.FloatField(null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='safety', to='places.city')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='places.country'),
        ),
        migrations.CreateModel(
            name='CountryHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tap_water_drinkable', models.BooleanField(null=True)),
                ('shower_filter_required', models.BooleanField(null=True)),
                ('yellow_fever_cert_required', models.BooleanField(null=True)),
                ('essential_vaccines', models.JSONField(blank=True, default=list)),
                ('vaccine_note', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health', to='places.country')),
            ],
        ),
        migrations.CreateModel(
            name='CulturalTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultural_tips', to='places.country')),
            ],
        ),
        migrations.CreateModel(
            name='TravelTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50, unique=True)),
                ('tag_class', models.CharField(db_column='class', max_length=30)),
                ('cities', models.ManyToManyField(blank=True, related_name='travel_tags', to='places.city')),
            ],
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('country', 'name'), name='uniq_city_in_country'),
        ),
    ]
