# Generated by Codex on 2026-06-24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_city_latitude_city_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')),
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                             related_name='environment_tag',
                                             to='places.traveltag')),
            ],
        ),
        migrations.AddField(
            model_name='environmenttag',
            name='cities',
            field=models.ManyToManyField(blank=True, related_name='environment_tags',
                                         to='places.city'),
        ),
    ]
