# Generated by Django 5.2.4 on 2026-06-23 03:16

import places.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='notes',
            field=models.JSONField(blank=True, default=list, encoder=places.models.KoreanJSONEncoder),
        ),
    ]
