# Generated by Django 5.2.4 on 2026-06-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_alter_recommendation_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationitem',
            name='category',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
