# Generated by Django 5.2.4 on 2026-06-23 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companion_type', models.CharField(choices=[('alone', '혼자'), ('friend', '친구'), ('family', '가족'), ('couple', '연인'), ('seeking', '동행 구함')], max_length=10)),
                ('companion_count', models.PositiveSmallIntegerField(default=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('local_language_ok', models.BooleanField(default=False)),
                ('accommodation_type', models.CharField(choices=[('hotel', '호텔/리조트/아파트'), ('guesthouse', '게스트하우스/호스텔'), ('capsule', '캡슐호텔')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='places.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='places.country')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
