# Generated by Django 5.2.4 on 2026-06-25 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        ('recommendations', '0003_recommendationitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='body',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='recommendation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_post', to='recommendations.recommendation'),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='title',
            field=models.CharField(default='', max_length=80),
        ),
    ]
